# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: nutritrack
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: 'Manar'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1121964'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1121964'

    # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:

